# Project: xiao_xiong_mao
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = xiao_xiong_mao_private.res
OBJ      = main.o $(RES)
BIN      = xiao_xiong_mao.exe
LINKOBJ  = "main.o" "xiao_xiong_mao_private.res"
CLEANOBJ = "main.o" "xiao_xiong_mao_private.res" "xiao_xiong_mao.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

xiao_xiong_mao.exe: $(OBJ)

	$(CC) $(LINKOBJ) -o "xiao_xiong_mao.exe" $(LIBS)

main.o: main.c
	$(CC) -c "main.c" -o "main.o" $(CFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

xiao_xiong_mao_private.res: xiao_xiong_mao_private.rc 
	$(WINDRES) -i "xiao_xiong_mao_private.rc" --input-format=rc -o "xiao_xiong_mao_private.res" -O coff $(WINDRESFLAGS) 

